# yaml 配置
version: "3.9"
services:
  mysql_server:
    image: "mysql:8.0.19"
    container_name: fastapi_mysql
    restart: always
    ports:
      - "13306:3306"
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: "localhost123"
      MYSQL_DATABASE: "app"
    volumes:
      - ./resources/init.sql:/data/application/init.sql
  redis_server:
    image: redis:7.0.11
    container_name: fastapi_redis
    restart: always
    ports:
      - "16379:6379"
  fastapi_server:
    container_name: fastapi
    build: .
    depends_on:
      - mysql_server
      - redis_server
    ports:
      - "8080:8080"
    restart: always
